language: php

php:
  - 5.5
  - 5.6

sudo: false

install:
  - bash install_phalcon.sh 2.0.9
  - composer update

script:
  - find src/ -type f -print0 | xargs -0 -n1 php -l
  - vendor/bin/phpcs --config-set show_warnings 0
  - vendor/bin/phpcs src/ --standard=psr2

notifications:
  email:
    - sid@sidroberts.co.uk
